{% set base_name = "libignition-tools" %}
{% set version = "1.4.1" %}
{% set name = base_name + version.split('.')[0] %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/ignitionrobotics/ign-tools/archive/ignition-tools_{{ version }}.tar.gz
    sha256: 6774ecf88bde9154fcbb52b491b85040e7c3d3e21986839cfe181001104a0cb9
    patches:
      - 73.patch
      - 74.patch

build:
  number: 1
  skip: false
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - make                               # [not win]
    - ruby                               # [not win]
    - ruby 2.7                           # [win]
    - ninja                              # [win]
    - cmake
    - pkg-config
  host:
    - backward-cpp
  run:
    - ruby                               # [not win]
    - ruby 2.7                           # [win]

test:
  commands:
    - test -f ${PREFIX}/lib/cmake/ignition-tools/ignition-tools-config.cmake  # [not win]
    - test -f ${PREFIX}/lib/libignition-tools-backward.so  # [linux]
    - test -f ${PREFIX}/lib/libignition-tools-backward.dylib  # [osx]
    - if not exist %PREFIX%\\Library\\lib\\cmake\\ignition-tools\\ignition-tools-config.cmake (exit 1)  # [win]
    - if not exist $PREFIX$\\Library\\lib\\ignition-tools-backward.lib (exit 1)  # [win]
    - if not exist $PREFIX$\\Library\\bin\\ignition-tools-backward.dll (exit 1)  # [win]

about:
  home: https://github.com/ignitionrobotics/ign-tools
  license: Apache-2.0
  license_file: LICENSE
  summary: Ignition Tools

extra:
  recipe-maintainers:
    - seanyen
    - wolfv
    - traversaro
    - j-rivero
