{% set base_name = "libignition-tools" %}
{% set version = "1.3.0" %}
{% set name = base_name + version.split('.')[0] %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/ignitionrobotics/ign-tools/archive/ignition-tools_{{ version }}.tar.gz
    sha256: dcad0011e9b0265c3c73e1c620512a7749a3b04dcffab389160e54c3761be1ca

build:
  number: 0
  skip: false
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - make                               # [not win]
    - ruby                               # [not win]
    - ruby 2.7                           # [win]
    - cmake
    - pkg-config
  run:
    - ruby                               # [not win]
    - ruby 2.7                           # [win]

test:
  commands:
    - test -f ${PREFIX}/lib/cmake/ignition-tools/ignition-tools-config.cmake  # [not win]
    - if exist %PREFIX%\\Library\\lib\\cmake\\ignition-tools\\ignition-tools-config.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/ignitionrobotics/ign-tools
  license: Apache-2.0
  license_file: LICENSE
  summary: Ignition Tools

extra:
  recipe-maintainers:
    - seanyen
    - wolfv
    - traversaro
    - j-rivero
